services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RELEASE_VERSION: release-v5.3
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace
      - vscode_server_cache:/home/esp/.vscode-server/
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb

volumes:
  vscode_server_cache:
